document.writeln("<div class=\"container-fluid\">");
document.writeln("    <div class=\"row state\">");
document.writeln("        <div>");
document.writeln("            <img src=\"http://47.115.92.110/lining/resource/images/ico-phone.png\" alt=\"\">");
document.writeln("            <h3>获取帮助</h3>");
document.writeln("            <p><a href=\"#\">联系我们</a> | <a href=\"#\">团购VIP</a></p>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <img src=\"http://47.115.92.110/lining/resource/images/ico-query.png\" alt=\"\">");
document.writeln("            <h3>防伪查询</h3>");
document.writeln("            <p><a href=\"#\">输入查询码</a></p>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("            <img src=\"http://47.115.92.110/lining/resource/images/ico-service.png\" alt=\"\">");
document.writeln("            <h3>售后服务</h3>");
document.writeln("            <p><a href=\"#\">使用说明</a></p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"row footer\">");
document.writeln("        <div class=\"text-center\">");
document.writeln("            <p>");
document.writeln("                温馨提示：近日有不法分子假冒+4006100011冒充李宁官方客服人员进行电话诈骗，请您提高警惕，注意保护个人账户信息，切勿泄漏他人。如遇类似问题，请勿回拨来电号码，直接拨打李宁客服电话400-610-0011询问。");
document.writeln("            </p>");
document.writeln("            <p>");
document.writeln("                <img src=\"http://47.115.92.110/lining/resource/images/gov.png\" alt=\"\">");
document.writeln("                <a href=\"#\">沪ICP备14035278号-2</a> © 1990-2020 李宁（中国）体育用品有限公司版权所有");
document.writeln("            </p>");
document.writeln("            <p>");
document.writeln("                <a href=\"\">关于李宁</a>");
document.writeln("                <a href=\"\">法律声明</a>");
document.writeln("                <a href=\"\">投资者关系 Investor Relations</a>");
document.writeln("                <a href=\"\">特许经营</a>");
document.writeln("                <a href=\"\">工商执照</a>");
document.writeln("                <a href=\"\" class=\"hotline\">客服热线</a>");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");