document.writeln("<div class=\"row navbar2\">");
document.writeln("    <nav class=\"navbar navbar-inverse\">");
document.writeln("        <div class=\"navbar-header\">");
document.writeln("            <a class=\"navbar-brand\" href=\"http://47.115.92.110/lining/index.html\">");
document.writeln("                <img alt=\"LI-NING 李宁\" src=\"http://47.115.92.110/lining/resource/images/logo-lining-nav2.png\">");
document.writeln("            </a>");
document.writeln("        </div>");
document.writeln("        <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">");
document.writeln("            <ul class=\"nav navbar-nav\">");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">系列 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <div class=\"container\">");
document.writeln("                            <div class=\"row\">");
document.writeln("                                <div");
document.writeln("                                    class=\"col-lg-offset-1 col-md-offset-1 col-sm-offset-1 col-lg-2 col-md-2 col-sm-2\">");
document.writeln("                                    <li>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/ico-nav-baskgetball.png\" alt=\"篮球\">");
document.writeln("                                        <br>");
document.writeln("                                        <p class=\"text-center\">");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">篮球</span></a>");
document.writeln("                                        </p>");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-2 col-md-2 col-sm-2\">");
document.writeln("                                    <li>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/ico-nav-running.png\" alt=\"跑步\">");
document.writeln("                                        <br>");
document.writeln("                                        <p class=\"text-center\">");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">跑步</span></a>");
document.writeln("                                        </p>");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-2 col-md-2 col-sm-2\">");
document.writeln("                                    <li>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/ico-nav-sportstyle.png\" alt=\"运动时尚\">");
document.writeln("                                        <br>");
document.writeln("                                        <p class=\"text-center\">");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">运动时尚</span></a>");
document.writeln("                                        </p>");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-2 col-md-2 col-sm-2\">");
document.writeln("                                    <li>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/ico-nav-trainning.png\" alt=\"训练\">");
document.writeln("                                        <br>");
document.writeln("                                        <p class=\"text-center\">");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">训练</span></a>");
document.writeln("                                        </p>");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-2 col-md-2 col-sm-2\">");
document.writeln("                                    <li>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/ico-nav-badmin.png\" alt=\"羽毛球\">");
document.writeln("                                        <br>");
document.writeln("                                        <p class=\"text-center\">");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">羽毛球</span></a>");
document.writeln("                                        </p>");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">李宁品牌 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <div class=\"container\">");
document.writeln("                            <div class=\"row\">");
document.writeln("                                <div class=\"col-lg-3 col-md-3 col-sm-3\">");
document.writeln("                                    <li class=\"brand_history\">");
document.writeln("                                        <br>");
document.writeln("                                        <p>");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">品牌历史</span> Brand");
document.writeln("                                                History</a>");
document.writeln("                                        </p>");
document.writeln("                                        <hr>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/nav-normal-brand-history.png\" alt=\"\"");
document.writeln("                                            class=\"img-responsive\">");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-3 col-md-3 col-sm-3\">");
document.writeln("                                    <li class=\"brand_event\">");
document.writeln("                                        <br>");
document.writeln("                                        <p>");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">品牌与赛事</span> Sponsor");
document.writeln("                                                Events</a>");
document.writeln("                                        </p>");
document.writeln("                                        <hr>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/nav-normal-brand-event.png\" alt=\"\"");
document.writeln("                                            class=\"img-responsive\">");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-3 col-md-3 col-sm-3\">");
document.writeln("                                    <li class=\"brand_star\">");
document.writeln("                                        <br>");
document.writeln("                                        <p>");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">品牌与明星</span> Celebrity");
document.writeln("                                                Endorsement</a>");
document.writeln("                                        </p>");
document.writeln("                                        <hr>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/nav-normal-brand-star.png\" alt=\"\"");
document.writeln("                                            class=\"img-responsive\">");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"col-lg-3 col-md-3 col-sm-3\">");
document.writeln("                                    <li class=\"brand_tech\">");
document.writeln("                                        <br>");
document.writeln("                                        <p>");
document.writeln("                                            <a href=\"#\"><span class=\"h4 text-danger\">产品科技</span> Product");
document.writeln("                                                Technology</a>");
document.writeln("                                        </p>");
document.writeln("                                        <hr>");
document.writeln("                                        <img src=\"http://47.115.92.110/lining/resource/images/nav-normal-brand-tech.png\" alt=\"\"");
document.writeln("                                            class=\"img-responsive\">");
document.writeln("                                    </li>");
document.writeln("                                </div>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">更多品牌 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more1.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more2.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more3.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more4.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more5.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more6.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more7.png\" alt=\"\"></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/nav-more8.png\" alt=\"\"></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">男子 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">新品和热卖</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger men_shoes\">鞋类</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger men_clothing\">服装</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger men_accessories\">配件/装备</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">主推专题</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">女子 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">新品和热卖</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger women_shoes\">鞋类</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger women_clothing\">服装</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger women_accessories\">配件/装备</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">主推专题</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">男童 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">新品和热卖</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger boys_shoes\">鞋类</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger boys_clothing\">服装</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">主推专题</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">女童 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">新品和热卖</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger girls_shoes\">鞋类</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger girls_clothing\">服装</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">主推专题</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"li_wade\">");
document.writeln("                    <a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/ico-wade-normal.png\" alt=\"\"> 韦德</a>");
document.writeln("                </li>");
document.writeln("                <li class=\"dropdown\">");
document.writeln("                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\"");
document.writeln("                        aria-haspopup=\"true\" aria-expanded=\"false\">官方报名 <span class=\"caret\"></span></a>");
document.writeln("                    <ul class=\"dropdown-menu\">");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">师资报名</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">冬令营报名</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">夏令营报名</span></a></li>");
document.writeln("                        <li role=\"separator\" class=\"divider\"></li>");
document.writeln("                        <li><a href=\"#\"><span class=\"text-danger\">青年一站式培训</span></a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li class=\"li_position\">");
document.writeln("                    <a href=\"#\"><img src=\"http://47.115.92.110/lining/resource/images/ico-position.png\" alt=\"\"> 门店查询</a>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <form class=\"navbar-form navbar-right\">");
document.writeln("                <div class=\"form-group\">");
document.writeln("                    <input type=\"text\" class=\"form-control searchInp\" placeholder=\"Search\">");
document.writeln("                </div>");
document.writeln("                <button type=\"button\" class=\"btn btn-danger searchBtn\"><span class=\"glyphicon glyphicon-search\"");
document.writeln("                        aria-hidden=\"true\"></span></button>");
document.writeln("            </form>");
document.writeln("        </div>");
document.writeln("    </nav>");
document.writeln("</div>");