document.writeln("<div class=\"row navbar1\">");
document.writeln("    <div class=\"col-lg-12\">");
document.writeln("        <div class=\"nav_l\">");
document.writeln("            <ul class=\"nav_l_li\">");
document.writeln("                <script src=\"http://47.115.92.110/lining/resource/js/jquery.cookie.js\"></script>");
// document.writeln("                <li><a href=\"http://47.115.92.110/lining/index.html\"><img src=\"http://47.115.92.110/lining/resource/images/LI-NING.png\" alt=\"\"></a></li>");
document.writeln("                <li><a href=\"http://47.115.92.110/lining/html/login.html\" class=\"login_href\">登录</a></li>");
document.writeln("                <li><a href=\"http://47.115.92.110/lining/html/register.html\" class=\"register_href\">注册</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("        <div class=\"nav_r\">");
document.writeln("            <ul>");
document.writeln("                <li><a href=\"http://47.115.92.110/lining/html/showcartInfo.html\"><span class=\"glyphicon glyphicon-shopping-cart\" aria-hidden=\"true\"></span> (<span class=\"cart_items\">0</span>)</a></li>");
document.writeln("                <li><a href=\"\">消息</a></li>");
document.writeln("                <li><a href=\"\">我的李宁</a></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</div>");